export const DESTINOS = [
    {'value': 'Afganistán', 'label':'Afganistán'},
    {'value': 'Albania', 'label':'Albania'},
    {'value': 'Alemania', 'label':'Alemania'},
    {'value': 'Andorra', 'label':'Andorra'},
    {'value': 'Angola', 'label':'Angola'},
    {'value': 'Anguila', 'label':'Anguila'},
    {'value': 'Antártida', 'label':'Antártida'},
    {'value': 'Antigua y Barbuda', 'label':'Antigua y Barbuda'},
    {'value': 'Antillas holandesas', 'label':'Antillas holandesas'},
    {'value': 'Arabia Saudí', 'label':'Arabia Saudí'},
    {'value': 'Argelia', 'label':'Argelia'},
    {'value': 'Argentina', 'label':'Argentina'},
    {'value': 'Armenia', 'label':'Armenia'},
    {'value': 'Aruba', 'label':'Aruba'},
    {'value': 'Australia', 'label':'Australia'},
    {'value': 'Austria', 'label':'Austria'},
    {'value': 'Azerbaiyán', 'label':'Azerbaiyán'},
    {'value': 'Bahamas', 'label':'Bahamas'},
    {'value': 'Bahrein', 'label':'Bahrein'},
    {'value': 'Bangladesh', 'label':'Bangladesh'},
    {'value': 'Barbados', 'label':'Barbados'},
    {'value': 'Bélgica', 'label':'Bélgica'},
    {'value': 'Belice', 'label':'Belice'},
    {'value': 'Benín', 'label':'Benín'},
    {'value': 'Bermudas', 'label':'Bermudas'},
    {'value': 'Bhután', 'label':'Bhután'},
    {'value': 'Bielorrusia', 'label':'Bielorrusia'},
    {'value': 'Birmania', 'label':'Birmania'},
    {'value': 'Bolivia', 'label':'Bolivia'},
    {'value': 'Bosnia y Herzegovina', 'label':'Bosnia y Herzegovina'},
    {'value': 'Botsuana', 'label':'Botsuana'},
    {'value': 'Brasil', 'label':'Brasil'},
    {'value': 'Brunei', 'label':'Brunei'},
    {'value': 'Bulgaria', 'label':'Bulgaria'},
    {'value': 'Burkina Faso', 'label':'Burkina Faso'},
    {'value': 'Burundi', 'label':'Burundi'},
    {'value': 'Cabo Verde', 'label':'Cabo Verde'},
    {'value': 'Camboya', 'label':'Camboya'},
    {'value': 'Camerún', 'label':'Camerún'},
    {'value': 'Canadá', 'label':'Canadá'},
    {'value': 'Chad', 'label':'Chad'},
    {'value': 'Chile', 'label':'Chile'},
    {'value': 'China', 'label':'China'},
    {'value': 'Chipre', 'label':'Chipre'},
    {'value': 'Ciudad estado del Vaticano', 'label':'Ciudad estado del Vaticano'},
    {'value': 'Colombia', 'label':'Colombia'},
    {'value': 'Comores', 'label':'Comores'},
    {'value': 'Congo', 'label':'Congo'},
    {'value': 'Corea', 'label':'Corea'},
    {'value': 'Corea del Norte', 'label':'Corea del Norte'},
    {'value': 'Costa del Marfíl', 'label':'Costa del Marfíl'},
    {'value': 'Costa Rica', 'label':'Costa Rica'},
    {'value': 'Croacia', 'label':'Croacia'},
    {'value': 'Cuba', 'label':'Cuba'},
    {'value': 'Dinamarca', 'label':'Dinamarca'},
    {'value': 'Djibouri', 'label':'Djibouri'},
    {'value': 'Dominica', 'label':'Dominica'},
    {'value': 'Ecuador', 'label':'Ecuador'},
    {'value': 'Egipto', 'label':'Egipto'},
    {'value': 'El Salvador', 'label':'El Salvador'},
    {'value': 'Emiratos Arabes Unidos', 'label':'Emiratos Arabes Unidos'},
    {'value': 'Eritrea', 'label':'Eritrea'},
    {'value': 'Eslovaquia', 'label':'Eslovaquia'},
    {'value': 'Eslovenia', 'label':'Eslovenia'},
    {'value': 'España', 'label':'España'},
    {'value': 'Estados Unidos', 'label':'Estados Unidos'},
    {'value': 'Estonia', 'label':'Estonia'},
    {'value': 'Etiopía', 'label':'Etiopía'},
    {'value': 'Ex-República Yugoslava de Macedonia', 'label':'Ex-República Yugoslava de Macedonia'},
    {'value': 'Filipinas', 'label':'Filipinas'},
    {'value': 'Finlandia', 'label':'Finlandia'},
    {'value': 'Francia', 'label':'Francia'},
    {'value': 'Gabón', 'label':'Gabón'},
    {'value': 'Gambia', 'label':'Gambia'},
    {'value': 'Georgia', 'label':'Georgia'},
    {'value': 'Georgia del Sur y las islas Sandwich del Sur', 'label':'Georgia del Sur y las islas Sandwich del Sur'},
    {'value': 'Ghana', 'label':'Ghana'},
    {'value': 'Gibraltar', 'label':'Gibraltar'},
    {'value': 'Granada', 'label':'Granada'},
    {'value': 'Grecia', 'label':'Grecia'},
    {'value': 'Groenlandia', 'label':'Groenlandia'},
    {'value': 'Guadalupe', 'label':'Guadalupe'},
    {'value': 'Guam', 'label':'Guam'},
    {'value': 'Guatemala', 'label':'Guatemala'},
    {'value': 'Guayana', 'label':'Guayana'},
    {'value': 'Guayana francesa', 'label':'Guayana francesa'},
    {'value': 'Guinea', 'label':'Guinea'},
    {'value': 'Guinea Ecuatorial', 'label':'Guinea Ecuatorial'},
    {'value': 'Guinea-Bissau', 'label':'Guinea-Bissau'},
    {'value': 'Haití', 'label':'Haití'},
    {'value': 'Holanda', 'label':'Holanda'},
    {'value': 'Honduras', 'label':'Honduras'},
    {'value': 'Hong Kong R. A. E', 'label':'Hong Kong R. A. E'},
    {'value': 'Hungría', 'label':'Hungría'},
    {'value': 'India', 'label':'India'},
    {'value': 'Indonesia', 'label':'Indonesia'},
    {'value': 'Irak', 'label':'Irak'},
    {'value': 'Irán', 'label':'Irán'},
    {'value': 'Irlanda', 'label':'Irlanda'},
    {'value': 'Isla Bouvet', 'label':'Isla Bouvet'},
    {'value': 'Isla Christmas', 'label':'Isla Christmas'},
    {'value': 'Isla Heard e Islas McDonald', 'label':'Isla Heard e Islas McDonald'},
    {'value': 'Islandia', 'label':'Islandia'},
    {'value': 'Islas Caimán', 'label':'Islas Caimán'},
    {'value': 'Islas Cook', 'label':'Islas Cook'},
    {'value': 'Islas de Cocos o Keeling', 'label':'Islas de Cocos o Keeling'},
    {'value': 'Islas Faroe', 'label':'Islas Faroe'},
    {'value': 'Islas Fiyi', 'label':'Islas Fiyi'},
    {'value': 'Islas Malvinas Islas Falkland', 'label':'Islas Malvinas Islas Falkland'},
    {'value': 'Islas Marianas del norte', 'label':'Islas Marianas del norte'},
    {'value': 'Islas Marshall', 'label':'Islas Marshall'},
    {'value': 'Islas menores de Estados Unidos', 'label':'Islas menores de Estados Unidos'},
    {'value': 'Islas Palau', 'label':'Islas Palau'},
    {'value': 'Islas Salomón', 'label':'Islas Salomón'},
    {'value': 'Islas Tokelau', 'label':'Islas Tokelau'},
    {'value': 'Islas Turks y Caicos', 'label':'Islas Turks y Caicos'},
    {'value': 'Islas Vírgenes EE.UU.', 'label':'Islas Vírgenes EE.UU.'},
    {'value': 'Islas Vírgenes Reino Unido', 'label':'Islas Vírgenes Reino Unido'},
    {'value': 'Israel', 'label':'Israel'},
    {'value': 'Italia', 'label':'Italia'},
    {'value': 'Jamaica', 'label':'Jamaica'},
    {'value': 'Japón', 'label':'Japón'},
    {'value': 'Jordania', 'label':'Jordania'},
    {'value': 'Kazajistán', 'label':'Kazajistán'},
    {'value': 'Kenia', 'label':'Kenia'},
    {'value': 'Kirguizistán', 'label':'Kirguizistán'},
    {'value': 'Kiribati', 'label':'Kiribati'},
    {'value': 'Kuwait', 'label':'Kuwait'},
    {'value': 'Laos', 'label':'Laos'},
    {'value': 'Lesoto', 'label':'Lesoto'},
    {'value': 'Letonia', 'label':'Letonia'},
    {'value': 'Líbano', 'label':'Líbano'},
    {'value': 'Liberia', 'label':'Liberia'},
    {'value': 'Libia', 'label':'Libia'},
    {'value': 'Liechtenstein', 'label':'Liechtenstein'},
    {'value': 'Lituania', 'label':'Lituania'},
    {'value': 'Luxemburgo', 'label':'Luxemburgo'},
    {'value': 'Macao R. A. E', 'label':'Macao R. A. E'},
    {'value': 'Madagascar', 'label':'Madagascar'},
    {'value': 'Malasia', 'label':'Malasia'},
    {'value': 'Malawi', 'label':'Malawi'},
    {'value': 'Maldivas', 'label':'Maldivas'},
    {'value': 'Malí', 'label':'Malí'},
    {'value': 'Malta', 'label':'Malta'},
    {'value': 'Marruecos', 'label':'Marruecos'},
    {'value': 'Martinica', 'label':'Martinica'},
    {'value': 'Mauricio', 'label':'Mauricio'},
    {'value': 'Mauritania', 'label':'Mauritania'},
    {'value': 'Mayotte', 'label':'Mayotte'},
    {'value': 'México', 'label':'México'},
    {'value': 'Micronesia', 'label':'Micronesia'},
    {'value': 'Moldavia', 'label':'Moldavia'},
    {'value': 'Mónaco', 'label':'Mónaco'},
    {'value': 'Mongolia', 'label':'Mongolia'},
    {'value': 'Montserrat', 'label':'Montserrat'},
    {'value': 'Mozambique', 'label':'Mozambique'},
    {'value': 'Namibia', 'label':'Namibia'},
    {'value': 'Nauru', 'label':'Nauru'},
    {'value': 'Nepal', 'label':'Nepal'},
    {'value': 'Nicaragua', 'label':'Nicaragua'},
    {'value': 'Níger', 'label':'Níger'},
    {'value': 'Nigeria', 'label':'Nigeria'},
    {'value': 'Niue', 'label':'Niue'},
    {'value': 'Norfolk', 'label':'Norfolk'},
    {'value': 'Noruega', 'label':'Noruega'},
    {'value': 'Nueva Caledonia', 'label':'Nueva Caledonia'},
    {'value': 'Nueva Zelanda', 'label':'Nueva Zelanda'},
    {'value': 'Omán', 'label':'Omán'},
    {'value': 'Panamá', 'label':'Panamá'},
    {'value': 'Papua Nueva Guinea', 'label':'Papua Nueva Guinea'},
    {'value': 'Paquistán', 'label':'Paquistán'},
    {'value': 'Paraguay', 'label':'Paraguay'},
    {'value': 'Perú', 'label':'Perú'},
    {'value': 'Pitcairn', 'label':'Pitcairn'},
    {'value': 'Polinesia francesa', 'label':'Polinesia francesa'},
    {'value': 'Polonia', 'label':'Polonia'},
    {'value': 'Portugal', 'label':'Portugal'},
    {'value': 'Puerto Rico', 'label':'Puerto Rico'},
    {'value': 'Qatar', 'label':'Qatar'},
    {'value': 'Reino Unido', 'label':'Reino Unido'},
    {'value': 'República Centroafricana', 'label':'República Centroafricana'},
    {'value': 'República Checa', 'label':'República Checa'},
    {'value': 'República de Sudáfrica', 'label':'República de Sudáfrica'},
    {'value': 'República Democrática del Congo Zaire', 'label':'República Democrática del Congo Zaire'},
    {'value': 'República Dominicana', 'label':'República Dominicana'},
    {'value': 'Reunión', 'label':'Reunión'},
    {'value': 'Ruanda', 'label':'Ruanda'},
    {'value': 'Rumania', 'label':'Rumania'},
    {'value': 'Rusia', 'label':'Rusia'},
    {'value': 'Samoa', 'label':'Samoa'},
    {'value': 'Samoa occidental', 'label':'Samoa occidental'},
    {'value': 'San Kitts y Nevis', 'label':'San Kitts y Nevis'},
    {'value': 'San Marino', 'label':'San Marino'},
    {'value': 'San Pierre y Miquelon', 'label':'San Pierre y Miquelon'},
    {'value': 'San Vicente e Islas Granadinas', 'label':'San Vicente e Islas Granadinas'},
    {'value': 'Santa Helena', 'label':'Santa Helena'},
    {'value': 'Santa Lucía', 'label':'Santa Lucía'},
    {'value': 'Santo Tomé y Príncipe', 'label':'Santo Tomé y Príncipe'},
    {'value': 'Senegal', 'label':'Senegal'},
    {'value': 'Serbia y Montenegro', 'label':'Serbia y Montenegro'},
    {'value': 'Sychelles', 'label':'Sychelles'},
    {'value': 'Sierra Leona', 'label':'Sierra Leona'},
    {'value': 'Singapur', 'label':'Singapur'},
    {'value': 'Siria', 'label':'Siria'},
    {'value': 'Somalia', 'label':'Somalia'},
    {'value': 'Sri Lanka', 'label':'Sri Lanka'},
    {'value': 'Suazilandia', 'label':'Suazilandia'},
    {'value': 'Sudán', 'label':'Sudán'},
    {'value': 'Suecia', 'label':'Suecia'},
    {'value': 'Suiza', 'label':'Suiza'},
    {'value': 'Surinam', 'label':'Surinam'},
    {'value': 'Svalbard', 'label':'Svalbard'},
    {'value': 'Tailandia', 'label':'Tailandia'},
    {'value': 'Taiwán', 'label':'Taiwán'},
    {'value': 'Tanzania', 'label':'Tanzania'},
    {'value': 'Tayikistán', 'label':'Tayikistán'},
    {'value': 'Territorios británicos del océano Indico', 'label':'Territorios británicos del océano Indico'},
    {'value': 'Territorios franceses del sur', 'label':'Territorios franceses del sur'},
    {'value': 'Timor Oriental', 'label':'Timor Oriental'},
    {'value': 'Togo', 'label':'Togo'},
    {'value': 'Tonga', 'label':'Tonga'},
    {'value': 'Trinidad y Tobago', 'label':'Trinidad y Tobago'},
    {'value': 'Túnez', 'label':'Túnez'},
    {'value': 'Turkmenistán', 'label':'Turkmenistán'},
    {'value': 'Turquía', 'label':'Turquía'},
    {'value': 'Tuvalu', 'label':'Tuvalu'},
    {'value': 'Ucrania', 'label':'Ucrania'},
    {'value': 'Uganda', 'label':'Uganda'},
    {'value': 'Uruguay', 'label':'Uruguay'},
    {'value': 'Uzbekistán', 'label':'Uzbekistán'},
    {'value': 'Vanuatu', 'label':'Vanuatu'},
    {'value': 'Venezuela', 'label':'Venezuela'},
    {'value': 'Vietnam', 'label':'Vietnam'},
    {'value': 'Wallis y Futuna', 'label':'Wallis y Futuna'},
    {'value': 'Yemen', 'label':'Yemen'},
    {'value': 'Zambia', 'label':'Zambia'},
    {'value': 'Zimbabue', 'label':'Zimbabue'},
]


